{
  "debianbug": 736247,
  "description": "Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called.",
  "releases": {
    "bullseye": {
      "fixed_version": "0.25-4",
      "repositories": {
        "bullseye": "0.25-5"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "fixed_version": "0.25-4",
      "repositories": {
        "buster": "0.25-5"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "jessie": {
      "fixed_version": "0.25-4",
      "repositories": {
        "jessie": "0.25-4",
        "jessie-security": "0.25-4+deb8u1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "sid": {
      "fixed_version": "0.25-4",
      "repositories": {
        "sid": "0.25-5"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "fixed_version": "0.25-4",
      "repositories": {
        "stretch": "0.25-4"
      },
      "status": "resolved",
      "urgency": "low"
    }
  },
  "scope": "local"
}