{
  "debianbug": 900182,
  "description": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.",
  "releases": {
    "bullseye": {
      "fixed_version": "3.5.5-3",
      "repositories": {
        "bullseye": "3.5.5-4"
      },
      "status": "resolved",
      "urgency": "high**"
    },
    "buster": {
      "fixed_version": "3.5.5-3",
      "repositories": {
        "buster": "3.5.5-4"
      },
      "status": "resolved",
      "urgency": "high**"
    },
    "sid": {
      "fixed_version": "3.5.5-3",
      "repositories": {
        "sid": "3.5.5-4"
      },
      "status": "resolved",
      "urgency": "high**"
    },
    "stretch": {
      "fixed_version": "0",
      "repositories": {
        "stretch": "3.4.3-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    }
  },
  "scope": "remote"
}