{
  "debianbug": 466663,
  "description": "lighttpd 1.4.18, and possibly other versions before 1.5.0, does not properly calculate the size of a file descriptor array, which allows remote attackers to cause a denial of service (crash) via a large number of connections, which triggers an out-of-bounds access.",
  "releases": {
    "bullseye": {
      "fixed_version": "1.4.18-2",
      "repositories": {
        "bullseye": "1.4.53-4"
      },
      "status": "resolved",
      "urgency": "medium"
    },
    "buster": {
      "fixed_version": "1.4.18-2",
      "repositories": {
        "buster": "1.4.53-4"
      },
      "status": "resolved",
      "urgency": "medium"
    },
    "jessie": {
      "fixed_version": "1.4.18-2",
      "repositories": {
        "jessie": "1.4.35-4+deb8u1",
        "jessie-security": "1.4.35-4+deb8u1"
      },
      "status": "resolved",
      "urgency": "medium"
    },
    "sid": {
      "fixed_version": "1.4.18-2",
      "repositories": {
        "sid": "1.4.53-4"
      },
      "status": "resolved",
      "urgency": "medium"
    },
    "stretch": {
      "fixed_version": "1.4.18-2",
      "repositories": {
        "stretch": "1.4.45-1"
      },
      "status": "resolved",
      "urgency": "medium"
    }
  },
  "scope": "remote"
}