{
  "debianbug": 434888,
  "description": "connections.c in lighttpd before 1.4.16 might accept more connections than the configured maximum, which allows remote attackers to cause a denial of service (failed assertion) via a large number of connection attempts.",
  "releases": {
    "bullseye": {
      "fixed_version": "1.4.16-1",
      "repositories": {
        "bullseye": "1.4.53-4"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "fixed_version": "1.4.16-1",
      "repositories": {
        "buster": "1.4.53-4"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "jessie": {
      "fixed_version": "1.4.16-1",
      "repositories": {
        "jessie": "1.4.35-4+deb8u1",
        "jessie-security": "1.4.35-4+deb8u1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "sid": {
      "fixed_version": "1.4.16-1",
      "repositories": {
        "sid": "1.4.53-4"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "fixed_version": "1.4.16-1",
      "repositories": {
        "stretch": "1.4.45-1"
      },
      "status": "resolved",
      "urgency": "low"
    }
  },
  "scope": "remote"
}