{
  "description": "lib/ansible/playbook/__init__.py in Ansible 1.2.x before 1.2.3, when playbook does not run due to an error, allows local users to overwrite arbitrary files via a symlink attack on a retry file with a predictable name in /var/tmp/ansible/.",
  "releases": {
    "bullseye": {
      "fixed_version": "0",
      "repositories": {
        "bullseye": "2.7.8+dfsg-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "buster": {
      "fixed_version": "0",
      "repositories": {
        "buster": "2.7.7+dfsg-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "jessie": {
      "fixed_version": "0",
      "repositories": {
        "jessie": "1.7.2+dfsg-2",
        "jessie-security": "1.7.2+dfsg-2+deb8u1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "sid": {
      "fixed_version": "0",
      "repositories": {
        "sid": "2.8.3+dfsg-1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "stretch": {
      "fixed_version": "0",
      "repositories": {
        "stretch": "2.2.1.0-2+deb9u1",
        "stretch-security": "2.2.1.0-2+deb9u1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    }
  },
  "scope": "local"
}