{
  "debianbug": 934026,
  "description": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.",
  "releases": {
    "bullseye": {
      "repositories": {
        "bullseye": "1:1.11.23-1~deb10u1"
      },
      "status": "open",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "1:1.11.23-1~deb10u1",
      "repositories": {
        "buster": "1:1.11.21-1",
        "buster-security": "1:1.11.23-1~deb10u1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "0",
      "repositories": {
        "jessie": "1.7.11-1+deb8u3",
        "jessie-security": "1.7.11-1+deb8u7"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "sid": {
      "fixed_version": "2:2.2.4-1",
      "repositories": {
        "sid": "2:2.2.4-1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "1:1.10.7-2+deb9u6",
      "repositories": {
        "stretch": "1:1.10.7-2+deb9u4",
        "stretch-security": "1:1.10.7-2+deb9u6"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}